name: LeafSkyblockCore
version: '1.3'
main: me.ipapervn.leafskyblockcore.LeafSkyblockCore
api-version: '1.21'
authors: [ipapervn]
softdepend: [SuperiorSkyblock2, PlaceholderAPI, DecentHolograms]
commands:
  leafskyblockcore:
    description: Main command for LeafSkyblockCore
    aliases: [lc, leafcore, leaf, leafskyblockcore]
    usage: /<command> [args]
  mcoins:
    description: MobCoins command
    aliases: [mobcoins]
    usage: /<command> [args]
